dist: bionic
language: java

matrix:
   include:
      #sonarcloud won't work with jdk8, as it requires jdk 11 or newer
      - jdk: openjdk8
        env: MAVEN_ARGS="coveralls:report"
      # coveralls plugin doesn't work with jdk 11 even if it should
      # assertj-swing and guice will give reflection warnings with jdk11
      - jdk: openjdk11
        env: MAVEN_ARGS="sonar:sonar -Dsonar.projectKey=Predictabowl_APT-Project-Aldinucci"



addons:
   sonarcloud:
      organization: "predictabowl"
      token: $SONAR_TOKEN

services:
   - docker
   - xvfb

#skip installation step
install: true

cache:
   directories:
      - .autoconf
      - $HOME/.m2
      - $HOME/.sonar/cache
      
      
script:
   - mvn -f bookstore-parent/pom.xml clean verify -Pjacoco,e2e-test,mutation-test $MAVEN_ARGS