dist: bionic
language: java

matrix:
   include:
      - jdk: openjdk8
        env: MAVEN_ARGS="coveralls:report"
       
      - jdk: openjdk11
        env: MAVEN_ARGS="sonar:sonar -Dsonar.projectKey=Predictabowl_APT-Project-Aldinucci"

#sonarcloud requires jdk 11 or newer
#coveralls requires jdk 8 is the project is set to it

addons:
   sonarcloud:
      organization: "predictabowl"
      token: $SONAR_TOKEN

#services:
#   - docker

#skip installation step
install: true

cache:
   directories:
      - .autoconf
      - $HOME/.m2
      - $HOME/.sonar/cache
      
      
script:
   #- ./travis-build
#   - mvn -f bookstore-core/pom.xml clean verify sonar:sonar -Dsonar.projectKey=Predictabowl_APT-Project-Aldinucci
#   - mvn -f bookstore-core/pom.xml clean verify coveralls:report
   - mvn -f bookstore-core/pom.xml clean verify $MAVEN_ARGS